//
//  PDF.Output Snapshot Tests.swift
//  swift-pdf-rendering
//

import Testing
import Tests_Inline_Snapshot
import Test_Snapshot_Primitives
import Layout_Primitives
import PDF_Rendering_Test_Support

@Suite
struct PDFOutputSnapshotTests {
    @Suite struct Snapshot {}
}

// MARK: - Snapshot

extension PDFOutputSnapshotTests.Snapshot {
    @Test
    func `sample document`() {
        struct SampleDocument: PDF.View {
            var body: some PDF.View {
                PDF.Stack(.vertical, spacing: 12) {
                    PDF.Text("PDF Rendering Test Document", state: .init(fontSize: 24))
                    PDF.Divider()
                    PDF.Text("Generated by swift-pdf-rendering", state: .init(fontSize: 12))
                    PDF.Spacer(20)

                    PDF.Text("1. Basic Text", state: .init(fontSize: 16))
                    PDF.Text(
                        "This is a paragraph of text that demonstrates basic text rendering. The text should wrap automatically when it exceeds the available width of the page content area."
                    )

                    PDF.Spacer(10)

                    PDF.Text("2. Font Sizes", state: .init(fontSize: 16))
                    PDF.Text("8pt text", state: .init(fontSize: 8))
                    PDF.Text("10pt text", state: .init(fontSize: 10))
                    PDF.Text("12pt text (default)", state: .init(fontSize: 12))
                    PDF.Text("14pt text", state: .init(fontSize: 14))
                    PDF.Text("18pt text", state: .init(fontSize: 18))

                    PDF.Spacer(10)

                    PDF.Text("3. Nested Layout", state: .init(fontSize: 16))
                    PDF.Stack(.vertical, spacing: 4) {
                        PDF.Text("Outer VStack - Item 1")
                        PDF.Stack(.vertical, spacing: 2) {
                            PDF.Text("  Inner VStack - Item A", state: .init(fontSize: 10))
                            PDF.Text("  Inner VStack - Item B", state: .init(fontSize: 10))
                            PDF.Text("  Inner VStack - Item C", state: .init(fontSize: 10))
                        }
                        PDF.Text("Outer VStack - Item 2")
                    }

                    PDF.Divider()
                    PDF.Text("End of test document", state: .init(fontSize: 10))
                }
            }
        }

        let document = PDF.Document(
            configuration: .init(
                version: .v1_7,
                info: .init(
                    title: "PDF Rendering Test",
                    author: "swift-pdf-rendering",
                    creator: "PDF.Output Tests"
                )
            )
        ) {
            SampleDocument()
        }

        snapshot(as: .pdf, named: "sample-document") { document }
    }

    @Test
    func `multi-page document`() {
        struct MultiPageDocument: PDF.View {
            var body: some PDF.View {
                PDF.Stack(.vertical, spacing: 8) {
                    PDF.Text("Multi-Page Test Document", state: .init(fontSize: 24))
                    PDF.Divider()

                    for i in 1...50 {
                        PDF.Text(
                            "Paragraph \(i): This is some sample text that will help fill the page. Each paragraph adds content that will eventually cause a page break when the content exceeds the available height.",
                            state: .init(fontSize: 11)
                        )
                    }

                    PDF.Divider()
                    PDF.Text("End of document", state: .init(fontSize: 10))
                }
            }
        }

        let document = PDF.Document(
            configuration: .init(
                version: .v1_7,
                info: .init(
                    title: "Multi-Page Test",
                    author: "swift-pdf-rendering"
                )
            )
        ) {
            MultiPageDocument()
        }

        snapshot(as: .pdf, named: "multi-page-document") { document }
    }

    @Test
    func `graphics document`() {
        let document = PDF.Document(
            configuration: .init(
                version: .v1_7,
                info: .init(
                    title: "Graphics Test",
                    author: "swift-pdf-rendering"
                )
            )
        ) {
            PDF.Stack(.vertical, spacing: 10) {
                PDF.Text("Graphics Test", state: .init(fontSize: 24))
                PDF.Divider()

                PDF.Text("RGB Colors:", state: .init(fontSize: 12))
                PDF.Stack(.vertical, spacing: 5) {
                    PDF.Text("Red")
                    PDF.Rectangle(width: 100, height: 30, fill: .red)
                    PDF.Text("Green")
                    PDF.Rectangle(width: 100, height: 30, fill: .green)
                    PDF.Text("Blue")
                    PDF.Rectangle(width: 100, height: 30, fill: .blue)
                }

                PDF.Spacer(20)

                PDF.Text("Grayscale:", state: .init(fontSize: 12))
                PDF.Stack(.vertical, spacing: 5) {
                    PDF.Text("Black")
                    PDF.Rectangle(width: 100, height: 30, fill: .black)
                    PDF.Text("Gray 50%")
                    PDF.Rectangle(width: 100, height: 30, fill: .gray50)
                    PDF.Text("Light Gray")
                    PDF.Rectangle(width: 100, height: 30, fill: .lightGray)
                }

                PDF.Spacer(20)

                PDF.Text("CMYK Colors:", state: .init(fontSize: 12))
                PDF.Stack(.vertical, spacing: 5) {
                    PDF.Text("Cyan")
                    PDF.Rectangle(width: 100, height: 30, fill: .cmyk(c: 1, m: 0, y: 0, k: 0))
                    PDF.Text("Magenta")
                    PDF.Rectangle(width: 100, height: 30, fill: .cmyk(c: 0, m: 1, y: 0, k: 0))
                    PDF.Text("Yellow")
                    PDF.Rectangle(width: 100, height: 30, fill: .cmyk(c: 0, m: 0, y: 1, k: 0))
                }

                PDF.Spacer(20)

                PDF.Text("Stroked Rectangle:", state: .init(fontSize: 12))
                PDF.Rectangle(width: 150, height: 50, stroke: .init(.black, width: 2))

                PDF.Spacer(10)

                PDF.Text("Filled and Stroked:", state: .init(fontSize: 12))
                PDF.Rectangle(
                    width: 150,
                    height: 50,
                    fill: .rgb(r: 0.9, g: 0.9, b: 1.0),
                    stroke: .init(.blue, width: 1)
                )
            }
        }

        snapshot(as: .pdf, named: "graphics-document") { document }
    }
}
