// PDF.Output Tests.swift
// Visual inspection tests - writes PDFs to /tmp

import Testing
import Foundation
@testable import PDF_Rendering
import PDF_Standard

@Suite
struct `PDF.Output Tests` {
    @Test
    func `Writes sample PDF to tmp`() throws {
        // Create a document with various elements
        struct SampleDocument: PDF.View {
            var body: some PDF.View {
                PDF.VStack(spacing: 12) {
                    // Title
                    PDF.Text("PDF Rendering Test Document", fontSize: 24, color: .black)

                    PDF.Divider()

                    // Subtitle
                    PDF.Text("Generated by swift-pdf-rendering", fontSize: 12, color: .gray50)

                    PDF.Spacer(20)

                    // Section 1: Basic Text
                    PDF.Text("1. Basic Text", fontSize: 16, color: .blue)
                    PDF.Text("This is a paragraph of text that demonstrates basic text rendering. The text should wrap automatically when it exceeds the available width of the page content area.")

                    PDF.Spacer(10)

                    // Section 2: Colors
                    PDF.Text("2. Colors", fontSize: 16, color: .blue)
                    PDF.Text("Black text", color: .black)
                    PDF.Text("Red text", color: .red)
                    PDF.Text("Green text", color: .green)
                    PDF.Text("Blue text", color: .blue)
                    PDF.Text("Gray text (50%)", color: .gray50)

                    PDF.Spacer(10)

                    // Section 3: Font Sizes
                    PDF.Text("3. Font Sizes", fontSize: 16, color: .blue)
                    PDF.Text("8pt text", fontSize: 8)
                    PDF.Text("10pt text", fontSize: 10)
                    PDF.Text("12pt text (default)", fontSize: 12)
                    PDF.Text("14pt text", fontSize: 14)
                    PDF.Text("18pt text", fontSize: 18)

                    PDF.Spacer(10)

                    // Section 4: Nested Stacks
                    PDF.Text("4. Nested Layout", fontSize: 16, color: .blue)
                    PDF.VStack(spacing: 4) {
                        PDF.Text("Outer VStack - Item 1")
                        PDF.VStack(spacing: 2) {
                            PDF.Text("  Inner VStack - Item A", fontSize: 10)
                            PDF.Text("  Inner VStack - Item B", fontSize: 10)
                            PDF.Text("  Inner VStack - Item C", fontSize: 10)
                        }
                        PDF.Text("Outer VStack - Item 2")
                    }

                    PDF.Divider()

                    PDF.Text("End of test document", fontSize: 10, color: .lightGray)
                }
            }
        }
        
        // Create document
        let pdfDocument = ISO_32000.Document.init(
            version: .v1_7,
            info: ISO_32000.Document.Info(
                title: "PDF Rendering Test",
                author: "swift-pdf-rendering",
                creator: "PDF.Output Tests"
            )
        ) {
            SampleDocument()
        }

        // Serialize to bytes
        let bytes = [UInt8](pdfDocument)

        // Write to /tmp
        let url = URL(fileURLWithPath: "/tmp/swift-pdf-rendering-test.pdf")
        try Data(bytes).write(to: url)

        print("PDF written to: \(url.path)")
        #expect(bytes.count > 0)
    }

    @Test
    func `Writes multi-page PDF to tmp`() throws {
        // Create a document that spans multiple pages
        struct MultiPageDocument: PDF.View {
            var body: some PDF.View {
                PDF.VStack(spacing: 8) {
                    PDF.Text("Multi-Page Test Document", fontSize: 24)
                    PDF.Divider()

                    // Generate enough content to span multiple pages
                    for i in 1...50 {
                        PDF.Text("Paragraph \(i): This is some sample text that will help fill the page. Each paragraph adds content that will eventually cause a page break when the content exceeds the available height.", fontSize: 11)
                    }

                    PDF.Divider()
                    PDF.Text("End of document", fontSize: 10, color: .gray50)
                }
            }
        }

        // Create document using the Document builder
        let pdfDocument = ISO_32000.Document(
            version: .v1_7,
            info: ISO_32000.Document.Info(
                title: "Multi-Page Test",
                author: "swift-pdf-rendering"
            )
        ) {
            MultiPageDocument()
        }

        let bytes = [UInt8](pdfDocument)

        let url = URL(fileURLWithPath: "/tmp/swift-pdf-rendering-multipage.pdf")
        try Data(bytes).write(to: url)

        print("Multi-page PDF written to: \(url.path)")

        #expect(bytes.count > 0)
    }

    @Test
    func `Writes graphics PDF to tmp`() throws {
        // Create a page with graphics using the document builder
        let pdfDocument = ISO_32000.Document(
            version: .v1_7,
            info: ISO_32000.Document.Info(
                title: "Graphics Test",
                author: "swift-pdf-rendering"
            )
        ) {
            PDF.VStack(spacing: 10) {
                PDF.Text("Graphics Test", font: .Helvetica.bold, fontSize: 24)
                PDF.Divider()

                PDF.Text("RGB Colors:", fontSize: 12)
                PDF.VStack(spacing: 5) {
                    PDF.Text("Red", color: .red)
                    PDF.Rectangle(width: 100, height: 30, fill: .red)

                    PDF.Text("Green", color: .green)
                    PDF.Rectangle(width: 100, height: 30, fill: .green)

                    PDF.Text("Blue", color: .blue)
                    PDF.Rectangle(width: 100, height: 30, fill: .blue)
                }

                PDF.Spacer(20)

                PDF.Text("Grayscale:", fontSize: 12)
                PDF.VStack(spacing: 5) {
                    PDF.Text("Black")
                    PDF.Rectangle(width: 100, height: 30, fill: .black)

                    PDF.Text("Gray 50%")
                    PDF.Rectangle(width: 100, height: 30, fill: .gray50)

                    PDF.Text("Light Gray")
                    PDF.Rectangle(width: 100, height: 30, fill: .lightGray)
                }

                PDF.Spacer(20)

                PDF.Text("CMYK Colors:", fontSize: 12)
                PDF.VStack(spacing: 5) {
                    PDF.Text("Cyan")
                    PDF.Rectangle(width: 100, height: 30, fill: .cmyk(c: 1, m: 0, y: 0, k: 0))

                    PDF.Text("Magenta")
                    PDF.Rectangle(width: 100, height: 30, fill: .cmyk(c: 0, m: 1, y: 0, k: 0))

                    PDF.Text("Yellow")
                    PDF.Rectangle(width: 100, height: 30, fill: .cmyk(c: 0, m: 0, y: 1, k: 0))
                }

                PDF.Spacer(20)

                PDF.Text("Stroked Rectangle:", fontSize: 12)
                PDF.Rectangle(width: 150, height: 50, stroke: .black, strokeWidth: 2)

                PDF.Spacer(10)

                PDF.Text("Filled and Stroked:", fontSize: 12)
                PDF.Rectangle(width: 150, height: 50, fill: .rgb(r: 0.9, g: 0.9, b: 1.0), stroke: .blue, strokeWidth: 1)
            }
        }

        let bytes = [UInt8](pdfDocument)

        let url = URL(fileURLWithPath: "/tmp/swift-pdf-rendering-graphics.pdf")
        try Data(bytes).write(to: url)

        print("Graphics PDF written to: \(url.path)")
        #expect(bytes.count > 0)
    }
}
